# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Note: This file is only expected to be occasionally edited, consider using
# Jekyll's data files feature for any data you need to update frequently.

# site main title
title:              notes from userspace

# the base hostname & protocol for your site, e.g. http://example.com
url:                https://jmeosbn.github.io

# the subpath of your site, e.g. /blog
baseurl:            /jekyll-new

# site info
author:             Jamie Osborne
# email:              your-email@domain.com
# description: > # this means to ignore newlines until next setting

twitter_username:   jmeosbn
github_username:    jmeosbn

# permalink style to use for posts
permalink:          /:title/

# posts pagination
paginate:           5

# custom marker to end excerpt
# excerpt_separator:  <!--more-->

# theme settings
minima:
  # refer to http://shopify.github.io/liquid/filters/date/
  date_format:      "%b %-d, %Y"

# Includes an icon in the footer for each username you enter
footer-links:
  email:
  show-rss:         yes
  twitter:          jmeosbn
  github:           jmeosbn
  linkedin:
  flickr:
  dribbble:
  facebook:
  instagram:
  pinterest:
  stackoverflow:    # users/50476/bart-kiers
  youtube:          # channel/<your_long_string> or user/<user-name>
  googleplus:       # username string that follows plus.google.com/

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
# - about.html

# theme
theme: minima

# build settings
markdown:           kramdown
kramdown:
  input:            GFM

# sass :expanded or minify using :compressed
sass:
  style:            :compressed

# exclude files from production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
